name: Upstream Sync

on:
  workflow_dispatch: # 只手動觸發

permissions:
  contents: write
  actions: write
  workflows: write # 允許同步 .github/workflows 裡的檔案

jobs:
  sync_latest_from_upstream:
    name: Sync latest commits from upstream repo
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.fork }}

    steps:
      # Step 1: Checkout target repo
      - name: Checkout target repo
        uses: actions/checkout@v4

      # Step 2: Sync upstream changes
      - name: Sync upstream changes
        id: sync
        uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
        with:
          upstream_sync_repo: LunaTechLab/MoonTV
          upstream_sync_branch: main
          target_sync_branch: main
          target_repo_token: ${{ secrets.GITHUB_TOKEN }}

      # Step 3: Delete old workflow runs
      - name: Delete workflow runs
        uses: Mattraks/delete-workflow-runs@main
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 0
          keep_minimum_runs: 2
